config/routes.rb
Rails.application.routes.draw do

   root 'companies#index'
   resources :regions
   resources :locations
   resources :companies
   resources :libraries
   resources :books
   resources :authors
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books , dependent: :destroy
  validates :name, presence: true, length: {minimum: 5}
  validates :gender, presence: true
  validates :age, presence: true , numericality: { only_numeric: true }
  validates :experience, presence: true , numericality: { only_numeric: true }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  def index
   @authors = Author.all
  end

  def show
  end

  def edit
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
     if @author.save
       redirect_to @author
       flash[:notice] =  "Author was successfully created."
     else
      render 'new' , status: :unprocessable_entity
     end
  end

  def update
    if @author.update(author_params)
      redirect_to @author
      flash[:notice] = "Author was successfully updated."
     else
     render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    flash[:notice] = "Author deleted successfully"
    redirect_to authors_path
  end

  private
     def set_author
       @author = Author.find(params[:id])
     end

     def author_params
       params.require(:author).permit(:name, :experience,:gender,:age)
     end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= render 'shared/errors', obj: @author %>

<%= form_with(model: @author, local: true) do |f| %>
  <p>
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Experience %>
    <%= f.text_field :experience %>
  </p>
  <p>
    <%= f.label :Gender%> <br/>
    <%= f.select :gender, %i{male female}, :prompt => 'Select', required: true, inclue_blank: 'Gender' %>
  </p>
  <p>
    <%= f.label :Age %>
    <%= f.text_field :age %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Cancel and Return to Authors page', authors_path %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.age%></td>
        <td><%= author.experience%></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Delete', author_path(author), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %> |
<%= link_to 'Home page' , companies_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'shared/errors', obj: @author %>
<%= form_with(model: @author, local: true) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Gender%> <br/>
    <%= f.select :gender, %i{male female}, :prompt => 'Select', required: true, inclue_blank: 'Gender' %>
  </p>
  <p>
    <%= f.label :Age %><br/>
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label :experience %><br/>
    <%= f.text_field :experience %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/authors/show.html.erb
<h1>Showing Author details</h1>
  <p><strong>Name: </strong><%= @author.name %></p>
  <p><strong>Gender:</strong><%=@author.gender %></p>
  <p><strong>Age:</strong><%= @author.age %></p>
  <p><strong>Experience:</strong><%= @author.experience%></p>
   <%= link_to 'Edit', edit_author_path(@author) %>
   <%= link_to 'Delete' , author_path(@author), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %>
   <%= link_to 'Return to author listing page', authors_path %> |
   <%= link_to 'Add new book' , new_book_path(author_id: @author.id) %>