config/routes.rb
Rails.application.routes.draw do

   root 'companies#index'
   resources :regions
   resources :locations
   resources :companies
   resources :libraries
   resources :books
   resources :authors
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :libraries, through: :locations
  has_many :regions ,dependent: :destroy
  validates :name , presence: true
  validates :website, presence: true
  validates :state, presence: true
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :company
  has_many :library_regions
  has_many :regions, through: :library_regions
  has_many :library_locations
  has_many :locations, through: :library_locations
  has_many :books , dependent: :destroy
  validates :name, presence: true
  validates :company, presence: true
  validates :region_ids, presence: true
  validates :location_ids, presence: true

end

#   validate :region_and_location_presence

#   def region_and_location_presence
#     errors.add(:regions, "must select at least one ") if regions.empty?
#     errors.add(:locations, "must select at least one ") if locations.empty?
#   end
# end

app/models/region.rb
class Region < ApplicationRecord
  has_many :locations , dependent: :destroy
  belongs_to :company
  validates :name, presence: true
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update destroy]

  def show
  end

  def index
    @libraries = Library.all
  end

  def edit
    if params[:library] && params[:library][:region_ids]
      @region = Array.new
      params[:library][:region_ids].each do |r|
        r = r.to_i
        @region << Region.find(r)
      end
     end
  end
  

 def new
    @library = Library.new(library_params)
    if params[:library] && params[:library][:region_ids]
     @region = Array.new
     params[:library][:region_ids].each do |r|
       r = r.to_i
       @region << Region.find(r)
     end
    end
  end

  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to library_url(@library), notice: "library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to library_url(@library), notice: "library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @library.destroy
    flash[:notice] =  "library deleted successfully."
    redirect_to libraries_path
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end

  def library_params
    params.fetch(:library, {}).permit(:name,:company_id, location_ids: [], region_ids: [])
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
<%= render 'shared/errors', obj: @library %>
  <%=form.hidden_field :company_id, value: params[:company_id]%>
  <p>
   <%=form.label "Name:"%>
   <%=form.text_field :name%></br>
  </p>
    <div data-controller="form-element">
      <%= form.button "Validate", formaction: new_library_path(@company_id), formmethod: :get, data: { turbo_frame: :location_field, form_element_target: "submitbtn"} %>
        <%= form.label("Select_Regions:")%>
        <%= form.collection_check_boxes :region_ids, Region.all,:id,:name, {include_blank: "-none-", include_hidden: false}, { data: { action: "change->form-element#remotesubmit"}, multiple: true} %>
    </div>

  <%= turbo_frame_tag :location_field do %>
    <% unless params[:library].nil? || @region.nil? %>
      <% @region.each do |region|%>
        <%= form.label "Locations in region:"%>
        <%= form.collection_check_boxes :location_ids, region.locations.order(:name),:id,:name, {include_blank: "-none-", include_hidden: false}, { multiple: true } %></br>
      <% end %>
    <%end%>
  <% end %>
  <%=form.submit%>
<%end%>

app/views/libraries/edit.html.erb
<% if @library.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>
    <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Editing library:</h1>
<%= form_with(model: @library, local: true) do |form| %>
   <p>
    <%=form.label "Name:"%>
    <%=form.text_field :name%></br>
   </p>
     <div data-controller="form-element">
       <%= form.button "Validate", formaction: edit_library_path(@library), formmethod: :get, data: { turbo_frame: :location_field, form_element_target: "submitbtn"} %>
         <%= form.label("Select_Regions:")%>
         <%= form.collection_check_boxes :region_ids, Region.all,:id,:name, {include_blank: "-none-", include_hidden: false}, { data: { action: "change->form-element#remotesubmit"}, multiple: true} %>
     </div>
    
  <%= turbo_frame_tag :location_field do %>
   <%  unless @region.nil? %>
     <% @region.each do |region|%>
       <%= form.label "Locations in region:"%>
       <%= form.collection_check_boxes :location_ids, region.locations.order(:name),:id,:name, {include_blank: "-none-", include_hidden: false}, { multiple: true } %></br>
     <% end %>
   <%end%>
  <% end %>
 <%=form.submit%>
<%end%>

<%= link_to 'Cancel and Return to libraries page', libraries_path %>

app/views/libraries/index.html.erb
<h1> Available libraries.</h1>

<table>
  <thead>
    <tr>
      <th>Library</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Delete', library_path(library), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
<%= link_to 'Authors listing page' , authors_path %>
<%= link_to 'Books listing page' , books_path%>
<%= link_to 'Home page', companies_path %>
</p>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render "form", library: @library %>


<br>


<p>
<%= link_to 'Cancel and Return to libraries page', libraries_path %>
</p>

app/views/libraries/show.html.erb
<h1>Library details</h1>
  <p><strong>Name: </strong><%= @library.name %></p>
    <%= link_to 'Edit', edit_library_path(@library) %> |
    <%= link_to 'Delete' , library_path(@library), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %>
  <% @library.regions.each do |region| %>
     <p><strong>Region:</strong> <%= region.name %></p>
  <% end %>
  <% @library.locations.each do|location| %>
     <p><strong>Location:</strong> <%= location.name %></p>
  <% end %>
   <%if @library.books.any?%>
      <b> <%=link_to 'Books', books_path(library_id: @library.id)%></b>
      <%else%>
     No books in library, <%= link_to ' Add books to library', new_book_path(library_id: @library.id)%></br>
    <% end %>
<p>
    <b>
       <%= link_to 'Back libraries page', libraries_path %> 
       <%= link_to 'Return to Comapnies listing page', companies_path %> |
    </b>
</p>