config/routes.rb
Rails.application.routes.draw do

   root 'companies#index'
   resources :regions
   resources :locations
   resources :companies
   resources :libraries
   resources :books
   resources :authors
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :libraries, through: :locations
  has_many :regions ,dependent: :destroy
  validates :name , presence: true
  validates :website, presence: true
  validates :state, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  def index
   @companies = Company.all
  end

  def show
  end

  def edit
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
     if @company.save
       redirect_to @company
       flash[:notice] =  "Company was successfully created."
     else
      render 'new' , status: :unprocessable_entity
     end
  end

  def update
    if @company.update(company_params)
      redirect_to @company
      flash[:notice] = "Company was successfully updated."
     else
     render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @company.destroy
    flash[:notice] = "Company deleted successfully"
    redirect_to companies_path
  end

  private
     def set_company
       @company = Company.find(params[:id])
     end

     def company_params
       params.require(:company).permit(:name,:website,:state)
     end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<h1>Edit Company</h1>
<%= render 'shared/errors', obj: @company %>

<%= form_with(model: @company, local: true) do |f| %>
  <p>
    <%= f.label :Name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Website %><br/>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :State %><br/>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%=link_to 'cancle and return to home page', companies_path  %>

app/views/companies/index.html.erb
<h1>Welcome to home page </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Location</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.state%></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Delete', company_path(company), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p>
<b>
<%=link_to 'Regions' , regions_path  %> |
<%=link_to 'Add new region', new_region_path%> |
<%=link_to 'Add new book', new_book_path%> |
<%=link_to 'Add a new company', new_company_path%> |
<%=link_to 'Add new author', new_author_path%> |
<%=link_to 'Libraries', libraries_path%> 
</b>
</p>

app/views/companies/new.html.erb
<h1>New Company</h1>
<%= render 'shared/errors', obj: @company %>

<%= form_with(model: @company, local: true) do |f| %>
  <p>
    <%= f.label :Name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Website %><br/>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :State%><br/>
    <%= f.text_field :state %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%=link_to 'cancle and return to home page', companies_path  %>

app/views/companies/show.html.erb
<h1>Showing Company details</h1>
  <p><strong>Name: </strong><%= @company.name %></p>
  <p><strong>Website: </strong><%= @company.website %></p>
  <p><strong>State: </strong><%= @company.state %></p>
  <%= link_to 'Edit', edit_company_path(@company) %> |
  <%= link_to 'Delete' , company_path(@company), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %>
<p>
 <b>
  <%= link_to 'Return to Comapnies listing page', companies_path %> |
  <%= link_to "Add Library", new_library_path(company_id: @company.id) %>
 </b>
</p>