config/routes.rb
Rails.application.routes.draw do

   root 'companies#index'
   resources :regions
   resources :locations
   resources :companies
   resources :libraries
   resources :books
   resources :authors
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :locations , dependent: :destroy
  belongs_to :company
  validates :name, presence: true
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[show edit update destroy]

  def show
  end

  def index
    @regions = Region.all
  end

  def edit
  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      flash[:notice] = "Region added successfully."
      redirect_to regions_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @region.update(region_params)
      flash[:notice] = "Region updated successfully."
      redirect_to @region
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @region.destroy
    flash[:notice] = " Region deleted successfully."
    redirect_to regions_path
  end

  private

  def set_region
    @region = Region.find(params[:id])
  end

  def region_params
    params.require(:region).permit(:name, :company_id)
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/edit.html.erb
<h1>Edit Regions</h1>
<%= render 'shared/errors', obj: @region %>

<%= form_with(model: @region, local: true) do |f| %>
  <p>
    <%= f.label :Region %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%=f.label :SelectCompany%>
    <%=f.collection_select :company_id, Company.order(:id),:id,:name%>
  </p>
    <%= f.submit %>
  </p>
<% end %>

<%=link_to 'cancle and return to home page', regions_path  %>

app/views/regions/index.html.erb
<h1>All regions</h1>

<table>
  <thead>
    <tr>
      <th>Region:</th>
      <th>Comapany:</th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.company.name%></td>
        <td><%= link_to 'Show' , region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Delete', region_path(region), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p>
 <b>
  <%=link_to 'Add new region', new_region_path%> |
  <%= link_to 'Return to home page' , companies_path %> |
  <%= link_to 'Add new location', new_location_path %> |
  <%= link_to 'View Locations', locations_path %>
 </b>
</p>

app/views/regions/new.html.erb
<%= render 'shared/errors', obj: @region %>

<h1>Adding region:</h1>
<%=form_with(model: @region, local: true) do |f|%>
  <p>
    <%=f.label :region%>
    <%=f.text_field :name%>
  </p>
  <p>
    <%=f.label :SelectCompany%>
    <%=f.collection_select :company_id, Company.order(:id),:id,:name ,  {include_blank: "-none-", include_hidden: false}%>
  </p>
    <%=f.submit%>
<%end%>
<p>
  <%= link_to "Cancle and back to regions home page" , regions_path %>
</p>

app/views/regions/show.html.erb
<h1>Regions</h1>
  <p><strong>Name: </strong><%= @region.name %></p>
  <%= link_to 'Edit', edit_region_path(@region) %>
  <%= link_to 'Delete' , region_path(@region), data: {turbo_method: :delete, turbo_confirm: 'Are you sure want to delete?'} %> |
  <%= link_to 'Return to home page', regions_path %>
  <p>
   <b>
     <%= link_to 'Add new location' , new_location_path(region_id: @region.id) %> |
     <%= link_to 'Regions Home page' , regions_path %>
   </b>
  </p>
  